# Generated by Django 3.2 on 2022-01-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='user_profile',
            new_name='user_number',
        ),
    ]
