# Generated by Django 4.0 on 2022-01-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychic',
            name='discredibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psychic',
            name='credibility',
            field=models.IntegerField(default=0),
        ),
    ]
